<template>
  <div class="p-4 md:p-8 h-full flex flex-col bg-themeWhite dark:bg-themeDark text-gray-900 dark:text-gray-100">
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 md:mb-8 border-b-2 border-themeGold pb-4 gap-4">
      <div>
        <h1 class="text-3xl md:text-4xl font-extrabold text-themeRed dark:text-red-500 uppercase tracking-widest">{{ $t('reports') || 'Reports' }}</h1>
        <p class="text-xs md:text-sm text-gray-500 dark:text-gray-400 mt-1">Manage and export system reports</p>
      </div>
      <div class="flex relative w-full md:w-auto gap-2 md:gap-4">
        <button @click="showFilter = !showFilter" class="px-4 py-2 bg-gray-100 dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-700 rounded-lg flex items-center justify-center hover:bg-gray-200 dark:hover:bg-gray-700 transition" title="Smart Filter">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-600 dark:text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" /></svg>
        </button>

        <!-- Smart Filter Dropdown -->
        <div v-if="showFilter" class="absolute top-full right-0 mt-2 w-64 bg-white dark:bg-themeDark rounded-lg shadow-xl border border-gray-200 dark:border-gray-800 z-50 p-4 animate-fade-in">
          <h3 class="text-sm font-bold border-b border-gray-200 dark:border-gray-800 pb-2 mb-3 text-themeGold">Smart Filter</h3>
          <div class="space-y-3 text-left">
            <div>
              <label class="block text-xs font-bold text-gray-500 mb-1">Report Type</label>
              <select class="w-full p-2 border border-gray-300 dark:border-gray-700 rounded text-sm bg-white dark:bg-gray-900 focus:outline-none">
                <option value="">All Types</option>
                <option value="sales">Sales Report</option>
                <option value="inventory">Inventory Report</option>
                <option value="adjustments">Adjustments Report</option>
              </select>
            </div>
            <div>
              <label class="block text-xs font-bold text-gray-500 mb-1">Date Range</label>
              <select class="w-full p-2 border border-gray-300 dark:border-gray-700 rounded text-sm bg-white dark:bg-gray-900 focus:outline-none">
                <option value="">All Time</option>
                <option value="today">Today</option>
                <option value="week">This Week</option>
                <option value="month">This Month</option>
              </select>
            </div>
            <div class="pt-2">
              <button @click="showFilter = false" class="w-full bg-themeRed text-white py-1.5 rounded text-sm font-bold hover:bg-red-800 transition">Apply Filters</button>
            </div>
          </div>
        </div>

        <button @click="showGenerateModal = true" class="flex-1 sm:flex-none bg-themeRed hover:bg-red-800 text-white px-4 md:px-6 py-2 rounded-lg font-bold shadow-md transition border border-red-900 whitespace-nowrap text-center flex items-center justify-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
          Generate Report
        </button>
      </div>
    </div>

    <div class="bg-white dark:bg-themeDark rounded-xl shadow-xl border border-gray-200 dark:border-gray-800 flex-grow overflow-hidden flex flex-col">
      <div class="overflow-x-auto flex-grow h-full">
        <table class="w-full text-left border-collapse whitespace-nowrap">
          <thead class="bg-gray-50 dark:bg-gray-900/50 text-gray-500 border-b-2 border-gray-100 dark:border-gray-800 sticky top-0 z-10">
            <tr>
              <th class="p-4 font-bold uppercase tracking-wider text-xs">ID</th>
              <th class="p-4 font-bold uppercase tracking-wider text-xs">Report Type</th>
              <th class="p-4 font-bold uppercase tracking-wider text-xs">Generated By</th>
              <th class="p-4 font-bold uppercase tracking-wider text-xs">Generated At</th>
              <th class="p-4 font-bold uppercase tracking-wider text-xs text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="report in mockReports" :key="report.id" class="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition">
              <td class="p-4 font-mono text-sm text-gray-500">#{{ report.id }}</td>
              <td class="p-4 font-bold text-md text-gray-800 dark:text-gray-200">
                {{ getReportTypeName(report.type_id) }}
              </td>
              <td class="p-4 text-sm text-gray-600 dark:text-gray-300">
                <div class="flex items-center gap-2">
                  <div class="w-6 h-6 rounded-full bg-themeGold flex items-center justify-center text-white font-bold text-xs">
                    {{ getUserInitials(report.generated_by) }}
                  </div>
                  {{ getUserName(report.generated_by) }}
                </div>
              </td>
              <td class="p-4 text-sm text-gray-500">
                {{ formatDate(report.generated_at) }}
              </td>
              <td class="p-4 text-right">
                <button @click="downloadReport(report)" class="text-themeGold hover:text-yellow-600 font-bold uppercase text-sm transition flex items-center justify-end gap-1 ml-auto">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Download
                </button>
              </td>
            </tr>
            <tr v-if="mockReports.length === 0">
              <td colspan="5" class="p-8 text-center text-gray-500">No reports generated yet.</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <!-- Generate Report Modal -->
    <div v-if="showGenerateModal" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div class="bg-white dark:bg-themeDark rounded-xl shadow-2xl w-full max-w-md overflow-hidden p-5 border border-gray-200 dark:border-gray-800">
        <h3 class="text-xl font-bold mb-4 dark:text-white border-b border-gray-200 dark:border-gray-800 pb-2">Generate New Report</h3>
        
        <div class="space-y-4 mb-6">
          <div>
            <label class="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1">Select Report Type <span class="text-themeRed">*</span></label>
            <select v-model="generateForm.type_id" class="w-full p-2.5 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 dark:text-white focus:outline-none focus:border-themeRed">
              <option disabled value="">-- Choose a report --</option>
              <option v-for="type in mockReportTypes" :key="type.id" :value="type.id">{{ type.name }}</option>
            </select>
          </div>

          <div class="grid grid-cols-2 gap-3">
            <div>
              <label class="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1">Start Date</label>
              <input type="date" v-model="generateForm.start_date" class="w-full p-2.5 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 dark:text-white focus:outline-none focus:border-themeRed" />
            </div>
            <div>
              <label class="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-1">End Date</label>
              <input type="date" v-model="generateForm.end_date" class="w-full p-2.5 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 dark:text-white focus:outline-none focus:border-themeRed" />
            </div>
          </div>
        </div>

        <div class="flex gap-3 justify-end">
          <button @click="showGenerateModal = false" class="px-4 py-2 text-gray-600 dark:text-gray-400 font-semibold hover:bg-gray-100 dark:hover:bg-gray-800 rounded transition">Cancel</button>
          <button @click="handleGenerateReport" :disabled="!generateForm.type_id" class="px-6 py-2 bg-themeRed hover:bg-red-800 disabled:bg-gray-400 disabled:cursor-not-allowed text-white rounded font-bold transition">
            Generate & Download
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const showFilter = ref(false)
const showGenerateModal = ref(false)

const generateForm = ref({
  type_id: '',
  start_date: '',
  end_date: ''
})

const mockReportTypes = {
  1: { id: 1, name: 'Sales Summary' },
  2: { id: 2, name: 'Inventory Status' },
  3: { id: 3, name: 'Adjustment Logs' }
}

const mockUsers = {
  1: { id: 1, name: 'Admin User' },
  2: { id: 2, name: 'Manager Seng' }
}

const mockReports = ref([])

const getReportTypeName = (typeId) => mockReportTypes[typeId]?.name || 'Unknown Report'
const getUserName = (userId) => mockUsers[userId]?.name || 'Unknown User'
const getUserInitials = (userId) => {
  const name = getUserName(userId)
  return name.split(' ').map(n => n[0]).join('').substring(0, 2).toUpperCase()
}

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toLocaleString()
}

const generateMockCSV = (filename) => {
  const csvContent = "data:text/csv;charset=utf-8,ID,Name,Value\n1,Test Item A,100\n2,Test Item B,250\n"
  const encodedUri = encodeURI(csvContent)
  const link = document.createElement("a")
  link.setAttribute("href", encodedUri)
  link.setAttribute("download", filename)
  document.body.appendChild(link) // Required for FF
  link.click()
  document.body.removeChild(link)
}

const handleGenerateReport = () => {
  if (!generateForm.value.type_id) return;

  const { showAlert } = useUiAlert()
  showAlert("Generating and downloading new report...", "Generate Report", "success")
  
  // Close modal
  showGenerateModal.value = false;

  // Mock adding it to the history log
  const newReport = {
    id: Math.floor(Math.random() * 1000) + 200,
    type_id: generateForm.value.type_id,
    generated_by: 1, // Assume Admin
    file_path: `/exports/new_report_${Date.now()}.csv`,
    generated_at: new Date().toISOString()
  }
  mockReports.value.unshift(newReport)

  // Actually download a mock file
  setTimeout(() => {
    generateMockCSV(`report_${generateForm.value.type_id}_${Date.now()}.csv`)
    // Reset form
    generateForm.value = { type_id: '', start_date: '', end_date: '' }
  }, 1000)
}

const downloadReport = (report) => {
  const reportName = getReportTypeName(report.type_id).replace(/\s+/g, '_').toLowerCase()
  generateMockCSV(`${reportName}_${report.id}.csv`)
}
</script>
